import Head from 'next/head'
import Header from "../components/Header"
import LotteryEntrance from '@/components/LotteryEntrance'



export default function Home() {
  return (
    <>
      <Head>
        <title>Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header/>
      <LotteryEntrance/>
      <main>
        
      </main>
    </>
  )
}
